# Generated by Django 2.1.4 on 2018-12-21 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_no', models.IntegerField()),
                ('e_name', models.CharField(max_length=64)),
                ('e_sal', models.FloatField()),
                ('e_addr', models.CharField(max_length=64)),
            ],
        ),
    ]
