# Generated by Django 2.1.4 on 2018-12-21 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_no', models.IntegerField()),
                ('m_name', models.CharField(max_length=65)),
                ('m_sal', models.FloatField()),
            ],
        ),
    ]
